version: "3.9"
services:
  db:
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_DB: vtescards
      POSTGRES_USER: bloodlibrary
      POSTGRES_PASSWORD: P4ssw0rd!
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - default_network

  backend:
    build: .
    depends_on:
      - db
    restart: always
    environment:
      DB_USER: bloodlibrary
      DB_PASSWORD: P4ssw0rd!
      DB_HOST: db
      STATICS_USER: ${STATICS_USER}
      STATICS_PASSWORD: ${STATICS_PASSWORD}
    networks:
       default_network:
       HTTP_SERVICES:

networks:
  default_network:
      driver: bridge
  HTTP_SERVICES:
          external: true

volumes:
  dbdata: