version: "3.9"
services:
  db:
    image: postgres:13.2
    volumes:
      - bloodlibrary_db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: vtescards
      POSTGRES_USER: bloodlibrary
      POSTGRES_PASSWORD: P4ssw0rd!
    networks:
      - default_network

  backend:
    build: .
    depends_on:
      - db
    restart: always
    environment:
      DB_USER: bloodlibrary
      DB_PASSWORD: P4ssw0rd!
      DB_HOST: db
    networks:
       default_network:
       HTTP_SERVICES:
         ipv4_address: "172.18.0.2"
    ports:
      - "8000:8000"

volumes:
  bloodlibrary_db: {}

networks:
  default_network:
      driver: bridge
  HTTP_SERVICES:
          external: true