# Generated by Django 4.2.4 on 2024-02-11 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0009_merge_20221223_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.TextField(max_length=128)),
                ('link', models.TextField(max_length=512)),
                ('release_date', models.DateField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.card')),
            ],
            options={
                'unique_together': {('card', 'shop')},
            },
        ),
    ]
