# Generated by Django 4.2.4 on 2024-10-03 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_cryptcard_abombwe_remove_cryptcard_animalism_and_more'),
        ('pod', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardshop',
            options={'ordering': ('shop',)},
        ),
        migrations.AlterField(
            model_name='cardshop',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='api.card'),
        ),
    ]
