# Generated by Django 4.2.4 on 2023-08-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('author', models.CharField(blank=True, max_length=128, null=True)),
                ('vekn_id', models.CharField(max_length=64)),
                ('vtesdecks_id', models.CharField(max_length=64, unique=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('num_players', models.IntegerField()),
                ('year', models.IntegerField(null=True)),
                ('vtesdecks_link', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
