# Generated by Django 3.0.2 on 2020-02-03 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('aka', models.CharField(max_length=32)),
                ('card_type', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CryptCard',
            fields=[
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Card')),
                ('clan', models.CharField(max_length=32)),
                ('advanced', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryCard',
            fields=[
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Card')),
                ('clan', models.CharField(max_length=32)),
                ('discipline', models.CharField(max_length=64)),
            ],
        ),
    ]
