# Generated by Django 3.0.2 on 2020-02-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='aka',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
