# Generated by Django 3.1.6 on 2021-03-23 16:09

from django.db import migrations
from multiprocessing.pool import ThreadPool
import requests


def check_image(set_id):
    img_url = 'https://statics.bloodlibrary.info/img/icons/{0}.gif'.format(set_id)
    rs = requests.head(img_url)
    if rs.status_code == 200:
        return set_id, img_url
    else:
        return None


def update_all_images(apps, schema_editor):
    Set = apps.get_model('api', 'Set')
    sets = list(Set.objects.all())
    parsed_sets = [zet.id for zet in sets]

    pool = ThreadPool(processes=16)
    results = pool.map(check_image, parsed_sets)
    pool.close()
    pool.join()

    indexed_objects = {cs.id: cs for cs in sets}
    objects_to_update = []
    for result in results:
        if result:
            zet = indexed_objects[result[0]]
            zet.icon = result[1]
            objects_to_update.append(zet)
    Set.objects.bulk_update(objects_to_update, ['icon'])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('api', '0004_load_card_set_images'),
    ]

    operations = [
        migrations.RunPython(update_all_images)
    ]
