# Generated by Django 3.1.13 on 2022-09-04 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_load_set_icons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['id']},
        ),
    ]
