# Generated by Django 3.1.13 on 2022-12-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220904_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateCard',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('alias', models.CharField(max_length=64)),
            ],
        ),
    ]
