# Generated by Django 3.1.13 on 2022-12-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_custom_cards'),
        ('api', '0008_load_privatecards'),
    ]

    operations = [
    ]
