# Generated by Django 4.2.16 on 2024-10-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_cryptcard_abombwe_remove_cryptcard_animalism_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cardset',
            constraint=models.UniqueConstraint(fields=('card', 'set', 'info', 'image'), name='unique_cardset'),
        ),
    ]
